<a href="https://colab.research.google.com/github/NoName-Tech-ui/Food_recognize/blob/main/BT_KHMT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
t= float(input('nhap t:'))
g, h0, v0= 9.8, 1.6, 14.2
h= h0 + v0*t -0.5*g*t**2
v= v0-g*t
print(h, v)

nhap t:0.5
7.475 9.299999999999999


# Mục mới

In [ ]:
t= float(input('nhap t:'))
g, h0, v0= 9.8, 1.6, 14.2
h= h0 + v0*t -0.5*g*t**2
v= v0-g*t
print(h, v)

nhap t:2.0
10.399999999999999 -5.400000000000002


In [ ]:
v0, a, z = 10, 2.5, 13/3
v= v0*(1-(z/(((a**2) + (z**2))**0.5)))
print(type(v))
print(v)

<class 'float'>
1.338144139513996


In [ ]:
v0, a, z = 10, 2.5, 26/3
v= v0*(1-(z/(((a**2) + (z**2))**0.5)))
print(v)

0.39176408819105335


In [ ]:
v0, a, z = 10, 2.5, 26/3
z=13
v= v0*(1-(z/(((a**2) + (z**2))**0.5)))
print(v)

0.17993553019352682


In [ ]:
import math
a= (2+ (math.e)**(2.8))/(math.sqrt(13) -2)
b= (1-(1+math.log(2, math.e))**(-3.5))/(1+math.sqrt(5))
c=math.sin((2-math.sqrt(2))/(2+math.sqrt(2)))
print(a,b,c)

11.488045914800644 0.26008973689431575 0.17073234104506005


In [ ]:
# 5.Tính diện tích tam giác cho biết đáy và chiều cao:
day=10
cao=12
s=(1/2)*day*cao
print(s)

60.0


In [ ]:
#6. Diện tích bề mặt và thể tích hình trụ
import math
r=5
h=3
Sxq= 2*math.pi*r*h
V= math.pi*(r**2)*h
print(Sxq, V)


94.24777960769379 235.61944901923448


In [ ]:
#7.
X1, Y1, X2, Y2= 3, 4, 5, 9
S= (Y2-Y1)/(X2-X1)
print(S)

2.5


In [ ]:
#8.
x1, y1, x2, y2= 3, 4, 5, 9
d= math.sqrt(((x2-x1)**2)+((y2-y1)**2))
print(d)

5.385164807134504


In [ ]:
#9. Tính 6!
import math
a=6
print(math.factorial(a))

720


In [ ]:
P1 = True
P2 = False
T1= P1 and (not P1)
T2= P2 and (not P2)
print("If P1 is true,", "P1 and (not P1) is", T1)
print("If P2 is false,", "P2 and (not P2) is", T2)

If P1 is true, P1 and (not P1) is False
If P2 is false, P2 and (not P2) is False


In [ ]:
import math
T= (((math.e)**2)*(math.sin(math.pi/6))+(math.log(3,math.e))*(math.cos(math.pi/9))-(5**3))
print(T)

-120.27311408976854


In [ ]:
P, Q, a, b = 1, 1, 10, 25
T = not(P) and not(Q)
print("NOT(P) AND NOT(Q) is ", T)
D = a<b and a==b
print("(a<b) AND (a=b) is", D)

NOT(P) AND NOT(Q) is  False
(a<b) AND (a=b) is False


In [ ]:
#1
s="123"
N=float(s)
print(type(s))
print(type(N))

<class 'str'>
<class 'float'>


In [ ]:
#2
s1="HELLO"
s2="hello"
print(s1.lower()==s2)
print(s1==s2.upper())

True
True


In [ ]:
#3
a,b="Engineering", "Book"
print('The world "Engineering" has',len(a), 'letters')
print('The world "Book" has',len(b), 'letters')

The world "Engineering" has 11 letters
The world "Book" has 4 letters


In [ ]:
#4
a="Python is great!"
print('Python' in a)

True


In [ ]:
#5
a="Python is great!"
print(a[10:15])

great


In [ ]:
#1
import numpy as np
r=np.linspace(0,29,9,dtype=int)
print(r)
print(r**2)
#(i)
print(r+r)
#(ii)
print(r*2)

[ 0  3  7 10 14 18 21 25 29]
[  0   9  49 100 196 324 441 625 841]
[ 0  6 14 20 28 36 42 50 58]
[ 0  6 14 20 28 36 42 50 58]


In [ ]:
#2
#(a)
import numpy as np
from math import *
a=np.ones(100,dtype=int)
print(a*e)
#(b)
b=np.linspace(0,360,361,dtype=int)
print(b)
#(c)
c=np.deg2rad(b)
print(c-b*np.pi/180)
#(d)
d=np.arange(12,17,0.2)
print(d)
#(e)
e=np.arange(12,17.2,0.2)
print(e)

[2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.7182

In [ ]:
#3
#(a)
import numpy as np
a=np.ones((8,8), dtype=int)
a[1:7,1:7:1]=0
print(a)
#(b)
b=np.ones((8,8), dtype=int)
b[0:8:2,0:8:2]=0
b[1:9:2,1:9:2]=0
print(b)
#(c)
c=np.arange(2,50,5)
c[c%3!=0]=-c[c%3!=0]
print(c)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[ -2  -7  12 -17 -22  27 -32 -37  42 -47]


In [ ]:
#19
import numpy as np
from math import *
x=np.array([1, 4, 3, 2, 9, 4])
y=np.array([2, 3, 4, 1, 2, 3])
u=x+y
v=x*y
w=x/y
z=np.sin(x)
r=8*np.sin(x)
s=5*np.sin(x*y)
p=x**y
print("u=", u)
print("v=", v)
print("w=", w)
print("z=", z)
print("r=", r)
print("s=", s)
print("p=", p)

u= [ 3  7  7  3 11  7]
v= [ 2 12 12  2 18 12]
w= [0.5        1.33333333 0.75       2.         4.5        1.33333333]
z= [ 0.84147098 -0.7568025   0.14112001  0.90929743  0.41211849 -0.7568025 ]
r= [ 6.73176788 -6.05441996  1.12896006  7.27437941  3.29694788 -6.05441996]
s= [ 4.54648713 -2.68286459 -2.68286459  4.54648713 -3.75493623 -2.68286459]
p= [ 1 64 81  2 81 64]


In [ ]:
#20
b=np.linspace(-10,10,100)
print(b)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

In [ ]:
#21
import numpy as np
array_a=np.array([-1, 0, 1, 2, 0, 3])
print(array_a[array_a>0])

[1 2 3]


In [ ]:
#22
import numpy as np
y=np.array([[3, 5, 3],
           [2, 2, 5],
           [3, 8, 9]])
y1=np.transpose(y)
print("y=",y)
print("y1=",y1)

y= [[3 5 3]
 [2 2 5]
 [3 8 9]]
y1= [[3 2 3]
 [5 2 8]
 [3 5 9]]


In [ ]:
#23
import numpy as np
a=np.zeros((2,4) ,dtype=int)
print("a23=",a)
#24
a[0:2,1:2]=1
print("a24=",a)


a23= [[0 0 0 0]
 [0 0 0 0]]
a24= [[0 1 0 0]
 [0 1 0 0]]


In [ ]:
#T2/21/10/2024:
#2
import numpy as np
def my_checher_board(n):
  m=np.zeros((n,n) ,dtype=int)
  m[::2,::2]=1
  m[1:n+1:2,1:n+1:2]=1
  return m
print( my_checher_board(4))

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


In [ ]:
#4
import numpy as np
def my_spilt_matrix(m):
 n=len(m[0])
 t=(n+1)//2
 m1=m[:,:t]
 m2=m[:,t:]
 return(m1,m2)
m=np.array([[1,2,3,4,5],
            [0,2,4,6,8],
            [1,3,5,7,9],
            [9,8,7,6,5]])
m1,m2=my_spilt_matrix(m)
print("m1=",m1)
print("m2=",m2)

m1= [[1 2 3]
 [0 2 4]
 [1 3 5]
 [9 8 7]]
m2= [[4 5]
 [6 8]
 [7 9]
 [6 5]]


In [ ]:
#6
import numpy as np
def my_n_odds(a):
  c=a[a%2==1]
  return c
print(len(my_n_odds(np.arange(100))))
print(len(my_n_odds(np.arange(2,100,2))))

50
0


In [ ]:
#7
import numpy as np
def my_twos(m,n):
   a=2*np.ones((m,n),  dtype=int)
   return a
print("TH1:", my_twos(3,2))
print("TH2:", my_twos(1,4))

TH1: [[2 2]
 [2 2]
 [2 2]]
TH2: [[2 2 2 2]]


In [ ]:
#13
import numpy as np
def dungsaichophep(A, a, dungsai):
  A=np.abs(np.array(A)-a)
  t=(A<dungsai)*np.arange(len(A))
  return t[t>0]
print("B=",dungsaichophep([0,1,2,3,4,5],2,1.5))
print("B=",dungsaichophep(np.arange(0,1.01,0.01),0.5,0.03))
print("B=",dungsaichophep([0,1,2,3],1.5,0.75))

B= [1 2 3]
B= [47 48 49 50 51 52]
B= [1 2]


In [ ]:

#14
import numpy as np
def gioihan(A, top, bottom):
  A = np.array(A)
  A[A <= bottom] = bottom
  A[A >= top] = top
  return A
print("B=",gioihan([0,1,2,3,4,5],4,1))

B= [1 1 2 3 4 4]


In [ ]:
import numpy as np
a=np.zeros((4,4), dtype=int)
a[1:5:2,1:5:2]=1
a[1:5:2,1:5:2]=1
print(a)

[[0 0 0 0]
 [0 1 0 1]
 [0 0 0 0]
 [0 1 0 1]]


In [ ]:
a,b,c=10,50,60
if a>b:
  if a>c:maxx=a
  else: maxx=c
else:
  if b>c:maxx=b
  else:maxx=c
print(maxx)

60


In [ ]:
a,b,c=30,10,20
maxx=a
if maxx<b: maxx=b
if maxx<c: maxx=c
print(maxx)

30


In [ ]:
a=int(input("nhap a: "))
b=int(input("nhap b: "))
c=eval(input("nhap c: "))
maxx=a
if maxx<b: maxx=b
if maxx<c: maxx=c
print(maxx)

nhap a: 3
nhap b: 1
nhap c: 10
10


In [ ]:
#T2/28/10/2024
#2
def my_mult_operation(a,b,operation):
  if operation == "plus":return a + b
  elif operation == "minus":
    return a - b
  elif operation == "mult":
    return a * b
  elif operation == "div":
    if b == 0:
      return "ERROR!!!"
    else:
      return a / b
  elif operation == "pow":
    if a==0:
      return "ERROR!!!"
    else:
      return a ** b
  else:
    return "ERROR!!!"
a=eval(input("a= "))
b=eval(input("b= "))
print("a+b=", my_mult_operation(a, b, "plus"))
print("a-b=", my_mult_operation(a, b, "minus"))
print("a*b=", my_mult_operation(a, b, "mult"))
print("a/b=", my_mult_operation(a, b, "div"))
print("a**b=", my_mult_operation(a, b, "pow"))

a= 6
b= 0
a+b= 6
a-b= 6
a*b= 0
a/b= ERROR!!!
a**b= 1


In [ ]:
#6
def my_letter_grader(percent):
  if percent>97: return "A+"
  elif percent>93: return "A"
  elif percent>90: return "A-"
  elif percent>87: return "B+"
  elif percent>83: return "B"
  elif percent>80: return "B-"
  elif percent>77: return "C+"
  elif percent>73: return "C"
  elif percent>70: return "C-"
  elif percent>67: return "D+"
  elif percent>63: return "D"
  elif percent>60: return "D-"
  else: return "F"
percent = float(input("percent="))
print("grade:" ,my_letter_grader(percent))

percent=93
grade: A-


In [ ]:
#7
def my_nuke_alarm(s1,s2,s3):
  if abs(s1-s2)>=10: return "Alarm!!!"
  if abs(s2-s3)>=10: return "Alarm!!!"
  if abs(s1-s3)>=10: return "Alarm!!!"
  else: return "Normal"
s1=eval(input("s1:"))
s2=eval(input("s2:"))
s3=eval(input("s3:"))
print(my_nuke_alarm(s1,s2,s3))

s1:23
s2:31
s3:10
Alarm!!!


In [ ]:
#8
from math import *
def my_n_roots(a,b,c):
  delta = b**2-4*a*c
  if delta > 0:
    x1 = (-b+sqrt(delta))/(2*a)
    x2 = (-b-sqrt(delta))/(2*a)
    r=[x1, x2]
    n_roots=2
    return n_roots, r
  elif delta == 0:
    r = -b/(2*a)
    n_roots=1
    return n_roots, [r]
  else: return -2
a=eval(input("a:"))
b=eval(input("b:"))
c=eval(input("c:"))
print(my_n_roots(a,b,c))

a:2
b:3
c:1
(2, [-0.5, -1.0])


In [ ]:
#3
def my_inside_triangle(x, y):
 if 0<=x<=1 and 0<=y<=1:
  if x==0 and y<=1: return "border"
  if y==0 and x<=1: return "boder"
  if x==y==0: "border"
  if x==y==1: return "outside"
  else: return "inside"
 else: return "outside"
x=eval(input("x="))
y=eval(input("y="))
print(my_inside_triangle(x, y))

x=1
y=3
outside


In [ ]:
#4
def my_make_size10(x):
  if len(x)>=10: return x[:10]
  else: return x + [0] * (10 - len(x))
x=eval(input("x="))
print(my_make_size10(x))

x=[1,2,3,4,5,6,7,8,9,11,12,13,15]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 11]


In [ ]:
#T2/11/11/2024:
#2
import numpy as np
def my_max(x):
  maxx=x[0]
  for i in x:
   if maxx<i:maxx=i
  return maxx
print(my_max(np.array([0,3,4,5,63,3,2,4])))

63


In [ ]:
#3
def my_n_max(x, n):
  if n<=0: return "ERROR"
  if n>len(x): "ERROR"
  result = []
  for i in range(n):
    maxx = max(x)
    result.append(maxx)
    x.remove(maxx)
  return result
print(my_n_max([1,2,3,5,3,522,42,32,9], 3))

[522, 42, 32]


In [ ]:
#4
from numpy import *
def my_trig_odd_even(m):
   q = np.zeros_like(m, dtype=float)
   for i in range(m.shape[0]):
    for j in range(m.shape[1]):
      if m[i, j] % 2 == 0:
        q[i, j] = sin(m[i, j])
      else:
        q[i, j] = cos(m[i, j])
   return q
print(my_trig_odd_even(np.array([[1,2,4,6,7,8],
                                 [1,2,4,6,3,1],
                                 [3,2,4,2,4,3],
                                 [3,5,2,5,1,5]])))

[[ 0.54030231  0.90929743 -0.7568025  -0.2794155   0.75390225  0.98935825]
 [ 0.54030231  0.90929743 -0.7568025  -0.2794155  -0.9899925   0.54030231]
 [-0.9899925   0.90929743 -0.7568025   0.90929743 -0.7568025  -0.9899925 ]
 [-0.9899925   0.28366219  0.90929743  0.28366219  0.54030231  0.28366219]]


In [ ]:
#6
def my_saving_plan(P0, i, goal):
  n = 0
  while P0 < goal:
    P0 *= (1 + i/100)
    n += 1
  return n
print("The number of years will takes:", my_saving_plan(1000, 7, 2000))

The number of years will takes: 11


In [ ]:
#8
from random import randint
def my_monopoly_dice():
  total = 0
  while True:
    dice1 = randint(1, 6)
    dice2 = randint(1, 6)
    total += dice1 + dice2
    if dice1 != dice2:
      break
  return total
print("Totals:", my_monopoly_dice())

Totals: 11


In [ ]:
#1
def so_chan_lon_nhat():
  while True:
    n = int(input("nhap n nguyen duong: "))
    if n <= 0:
      print("nhap lai")
    so_chan=[]
    i=0
    for i in range(n):
      a = int(input(f"nhap so nguyen thu {i+1}: "))
      if a % 2 == 0: so_chan.append(a)
    if so_chan: print("so chan lon nhat la:", max(so_chan))
    else: print("ko co so chan")
    tiep_tuc = input("ban muon tiep tuc ko?(nhan y de tiep tuc): ")
    if tiep_tuc != 'y':
      break
print(so_chan_lon_nhat())

nhap n nguyen duong: 4
nhap so nguyen thu 1: 23
nhap so nguyen thu 2: 65
nhap so nguyen thu 3: 67
nhap so nguyen thu 4: 4
so chan lon nhat la: 4
ban muon tiep tuc ko?(nhan y de tiep tuc): y
nhap n nguyen duong: 6
nhap so nguyen thu 1: 6
nhap so nguyen thu 2: 5
nhap so nguyen thu 3: 4
nhap so nguyen thu 4: 3
nhap so nguyen thu 5: 8
nhap so nguyen thu 6: 43
so chan lon nhat la: 8
ban muon tiep tuc ko?(nhan y de tiep tuc): n
None


In [ ]:
#2a
def so_lan_xuat_hien(a):
  dem={}
  for i in a:
    if i.isalpha():
      i=i.lower()
      if i in dem:
        dem[i]+=1
      else: dem[i]=1
  return dem
print(so_lan_xuat_hien("Lap trinh Python va AI - Truong Cong nghe va thiet ke - Dai Hoc UEH Thanh Pho Ho Chi Minh."))

{'l': 1, 'a': 6, 'p': 3, 't': 6, 'r': 2, 'i': 6, 'n': 7, 'h': 12, 'y': 1, 'o': 6, 'v': 2, 'u': 2, 'g': 3, 'c': 3, 'e': 4, 'k': 1, 'd': 1, 'm': 1}


In [ ]:
#2b
def so_lan_xuat_hien_tu(a):
  tu = a.split()
  dem = {}
  for i in tu:
    i = i.lower()
    if i in dem:
      dem[i] += 1
    else:
      dem[i] = 1
  return dem
print(so_lan_xuat_hien_tu("Lap trinh Python va AI - Truong Cong nghe va thiet ke - Dai Hoc UEH Thanh Pho Ho Chi Minh."))


{'lap': 1, 'trinh': 1, 'python': 1, 'va': 2, 'ai': 1, '-': 2, 'truong': 1, 'cong': 1, 'nghe': 1, 'thiet': 1, 'ke': 1, 'dai': 1, 'hoc': 1, 'ueh': 1, 'thanh': 1, 'pho': 1, 'ho': 1, 'chi': 1, 'minh.': 1}


In [ ]:
#3
def kt_mk(mk):
  if len(mk) < 8:
        return False
  chu_cai = False
  chu_so = False
  ky_tu_db = False
  for i in mk:
      if i.isalpha():
          chu_cai = True
      elif i.isdigit():
          chu_so = True
      elif i in "!@#$%^&*":
          ky_tu_db = True
  return chu_cai and chu_so and ky_tu_db
mk=input("nhap mat khau:")
if kt_mk(mk):print("mk manh")
else:print("mk yeu")

nhap mat khau:kjsfakfjjdls@$325
mk manh


In [ ]:
def quan_ly_hang_hoa():
    hang_hoa = {}
    while True:
        print("1. Nhập thêm hàng hóa")
        print("2. Thống kê số lượng")
        print("3. Thoát")
        chon = int(input("Chọn chức năng: "))

        if chon == 1:
            ten_hang = input("Nhập tên hàng hóa: ")
            so_luong = int(input("Nhập số lượng: "))
            if ten_hang in hang_hoa:
                hang_hoa[ten_hang] += so_luong
            else:
                hang_hoa[ten_hang] = so_luong
            print("Đã cập nhật thông tin hàng hóa.")

        elif chon == 2:
            print("Thống kê số lượng hàng hóa:")
            for hang, so_luong in hang_hoa.items():
                print(f"{hang}: {so_luong}")

        elif chon == 3:
            break

        else:
            print("Lựa chọn không hợp lệ. Vui lòng chọn lại.")

if __name__ == "__main__":
    quan_ly_hang_hoa()

In [ ]:
def F(a, b=0):
    tong = 0
    for x in a:
        if x == 0:
            tong = 1
        else:
            tong = tong + x**b
    return tong

A = F([0])
B = F([1, 2, 3])
C = F([1, 2, 3], 2)
print(A,B,C)

1 3 14


In [ ]:
import java.util.Random;

public class SaTsp {

    private double[][] costMatrix;
    private int numOfCity;
    private double T, pi, epsilon;

    // Constructor to initialize the parameters and start the simulated annealing algorithm
    public SaTsp(double[][] cost, double T, double pi, double epsilon) {
        this.costMatrix = cost;
        this.T = T;
        this.pi = pi;
        this.epsilon = epsilon;
        this.numOfCity = this.costMatrix.length;
        sa();
    }

    // Simulated annealing algorithm to find the minimum traveling cost
    private void sa() {
        long t0 = System.currentTimeMillis();
        int[] currentSolution = initialSolution();
        int[] bestSolution = copy(currentSolution);
        double bestCost = fit(bestSolution);
        double currentCost = bestCost;
        Random random = new Random();

        while (T >= epsilon) {
            int[] neighborSolution = generateNeighbor(currentSolution);
            double neighborCost = fit(neighborSolution);

            if (neighborCost < currentCost || (random.nextDouble() < Math.exp((currentCost - neighborCost) / T))) {
                currentSolution = copy(neighborSolution);
                currentCost = neighborCost;
            }

            if (currentCost < bestCost) {
                bestCost = currentCost;
                bestSolution = copy(currentSolution);
                displayBestSolution(bestSolution, bestCost, t0);
            }

            T *= pi;
        }
    }

    // Calculates the fitness (total cost) of a solution path
    private double fit(int[] solution) {
        double totalCost = 0;
        for (int i = 0; i < solution.length - 1; i++) {
            totalCost += this.costMatrix[solution[i]][solution[i + 1]];
        }
        totalCost += this.costMatrix[solution[solution.length - 1]][solution[0]];
        return totalCost;
    }

    // Generates an initial random solution
    private int[] initialSolution() {
        int[] solution = new int[this.numOfCity];
        for (int i = 0; i < solution.length; i++) {
            solution[i] = i;
        }
        shuffleArray(solution);
        return solution;
    }

    // Generates a neighboring solution by swapping two cities in the current solution
    private int[] generateNeighbor(int[] solution) {
        int[] neighbor = copy(solution);
        Random random = new Random();
        int a = random.nextInt(neighbor.length);
        int b = random.nextInt(neighbor.length);
        int temp = neighbor[a];
        neighbor[a] = neighbor[b];
        neighbor[b] = temp;
        return neighbor;
    }

    // Shuffles the array randomly to create an initial solution
    private void shuffleArray(int[] array) {
        Random random = new Random();
        for (int i = array.length - 1; i > 0; i--) {
            int j = random.nextInt(i + 1);
            int temp = array[i];
            array[i] = array[j];
            array[j] = temp;
        }
    }

    // Creates a copy of an array (solution path)
    public int[] copy(int[] solution) {
        int[] copy = new int[solution.length];
        System.arraycopy(solution, 0, copy, 0, solution.length);
        return copy;
    }

    // Displays the best solution found so far
    private void displayBestSolution(int[] bestSolution, double bestCost, long startTime) {
        System.out.println("Best cost: " + bestCost);
        for (int city : bestSolution) {
            System.out.print(city + "\t");
        }
        System.out.println();
        System.out.println("Time elapsed: " + (System.currentTimeMillis() - startTime) / 1000 + " seconds\n");
    }

    // Main method to run the program
    public static void main(String[] args) {
        double[][] cost = {
            {0, 10, 26, 13, 33, 11, 35, 26, 34, 11, 44, 23, 12, 29, 23, 44},
            {25, 0, 33, 20, 31, 12, 28, 33, 32, 12, 15, 19, 44, 45, 44, 10},
            {35, 26, 0, 36, 34, 41, 16, 43, 16, 13, 28, 11, 23, 30, 39, 22},
            {29, 46, 50, 0, 21, 33, 49, 25, 35, 40, 39, 40, 25, 14, 11, 21},
            {38, 31, 21, 11, 0, 21, 32, 19, 50, 26, 50, 32, 47, 24, 38, 21},
            {16, 31, 40, 35, 50, 0, 42, 21, 22, 13, 32, 44, 23, 40, 48, 34},
            {42, 25, 21, 44, 36, 28, 0, 13, 22, 28, 47, 14, 46, 11, 40, 44},
            {26, 31, 32, 19, 13, 37, 30, 0, 26, 31, 34, 30, 15, 36, 10, 15},
            {35, 21, 11, 19, 49, 20, 37, 29, 0, 30, 38, 21, 22, 49, 40, 46},
            {22, 34, 11, 44, 27, 16, 49, 30, 32, 0, 44, 32, 32, 44, 39, 26},
            {33, 41, 34, 49, 46, 37, 50, 38, 45, 11, 0, 39, 27, 32, 15, 26},
            {30, 21, 41, 48, 44, 43, 14, 26, 17, 32, 24, 0, 26, 24, 40, 47},
            {11, 29, 19, 38, 20, 23, 11, 10, 23, 38, 25, 31, 0, 40, 45, 47},
            {13, 46, 40, 30, 32, 47, 19, 29, 40, 24, 32, 23, 32, 0, 28, 36},
            {47, 40, 40, 38, 10, 31, 27, 25, 29, 26, 13, 40, 17, 46, 0, 16},
            {12, 13, 14, 39, 49, 38, 43, 24, 24, 50, 12, 23, 25, 44, 10, 0}
        };

        // Initial temperature calculation
        double initialTemperature = 0;
        for (int i = 0; i < cost.length; i++) {
            initialTemperature += 2 * cost[0][i];
        }

        // Create SaTsp instance and start simulated annealing
        SaTsp saTsp = new SaTsp(cost, initialTemperature, 0.99999999, 0.001);
    }
}
